# name: batari-backend

# on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy using ssh
#         uses: appleboy/ssh-action@master
#         with:
#           host: '72.60.76.188'
#           username: 'root'
#           key: ${{ secrets.BATARI_SSH_PRIVATE_KEY }}
#           port: 22
#           script: |
#             git config --global --add safe.directory /batari/batari_backend/src
            
#             curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
#             apt install -y nodejs
#             npm install -g npm@latest
#             # Ensure pm2 is installed
#             # Ensure pm2 is installed
#             npm install -g pm2
#             # Change to the project directory and execute the build script
#             cd batari/batari_backend/src
#             #chmod +x ./build.sh
#             #chmod +x ./build.sh
#             #./build.sh
#             git pull origin main
#             pm2 delete batari_backend
#             pm2 start server.js -n batari_backend

name: force-clean-deploy
on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Force Clean Deploy
        uses: appleboy/ssh-action@master
        with:
          host: '72.60.76.188'
          username: 'root'
          key: ${{ secrets.BATARI_SSH_PRIVATE_KEY }}
          script: |
            cd /root/batari/batari_backend
            
            echo "=== Reset Everything ==="
            git fetch origin
            git reset --hard origin/main
            
            echo "=== Clean Install ==="
            rm -rf node_modules
            npm install
            
            echo "=== Restart Application ==="
            pm2 delete batari_backend || true
            cd src
            pm2 start server.js --name batari_backend
            
            echo "=== Save PM2 ==="
            pm2 save
            
            echo "✅ Deployment completed!"
            echo "📝 Latest commit: $(git log --oneline -1)"